### ISSUE TITLE
[API] managing product attributes from API

### ISSUE THREAD

**Issue by laurentdabbb** [Sylius/Sylius#13414]
Hi,

Sorry in advance, if I missed an already opened issue about managing productAttribute from API. 
I can't figure how to retrieve a productAttribute value from API. This feature seems to be actually missing.

I think this should be added to the #11250 roadmap about features requested to the community.

Complete CRUD features would be nice, but in a first time simply retrieving productAttribute values attached to a product would be great.

It's quite easy for simple productAttribute type like "text", but a little bit more complex for "select" which values are stored in a serialized format. 

I don't know if product attributes should be directly available form product serialization or only from a specific endpoint (subresource) for performance reasons.

Thank you and sorry again if a similar issue already exists.

**Comment by Zales0123** [comment]
Hello @laurentdabbb. Indeed, it would be great to do it :) However, we're currently focusing on Shop API, so it's not a priority for us now. **However**, if you would like to give it a try and open a PR with such a change, we would be happy to merge it and/or help with potential problems. Tip: regarding different structures for different types, you can take a look at CatalogPromotion's API, as this is a similar case 🖖 🐎

**Comment by laurentdabbb** [comment]
OK, thanks for your feedback.
I implemented a new endpoint specifically to what I need, so not enought generic to open a PR ;-)
I will take a look to CatalogPromotion's API.

Thx

**Comment by coldic3** [comment]
Hey @laurentdabbb. I come with a small update 💃 Recently we added GET methods for retrieving product attributes in the shop (here https://github.com/Sylius/Sylius/pull/13928). It's still not fully covered CRUD but maybe you find it useful :slightly_smiling_face: You can test it out on the master demo https://master.demo.sylius.com/api/v2 if you wish. These endpoints should appear in the next Sylius/Sylius release.

**Comment by NoResponseMate** [comment]
Hi @laurentdabbb 👋 

Management of product attributes via the API has been added in 1.13.

Cheers 🍻
