### ISSUE TITLE
SyliusResource not work in stand-alone mode

### ISSUE THREAD

**Issue by Shine-neko** [Sylius/Sylius#2491]
Should take stock of the dependencies. Actually this is nonsense. 

SyliusResourceBundle need SyliusTranslationBundle
SyliusTranslationBundle need SyliusResourceBundle
SyliusResourceBundle need SyliusLocalBundle
SyliusLocalBundle need SyliusResourceBundle

**Comment by Shine-neko** [comment]
@pjedrzejewski  @stloyd @aRn0D

**Comment by pjedrzejewski** [comment]
@Shine-neko Yes, I will be taking care of this today/tomorrow!

**Comment by amenophis** [comment]
@pjedrzejewski some news ??

**Comment by jimbocoder** [comment]
For now, this seems to do the trick:

```yaml
parameters:
    sylius.locale: "%locale%"
    sylius.translation.default.mapping:
      translatable: []
      translation: []
```

**Comment by michalmarcinkowski** [comment]
This should resolve the problem for now  https://github.com/Lakion/Lionframe/commit/a61a7370e6067a39d9e1a8ea682da42ab5c89040

**Comment by Shine-neko** [comment]
@michalmarcinkowski missing documentation ? :D. This does not solve the problem ...

**Comment by Shine-neko** [comment]
@pjedrzejewski  ?

**Comment by aRn0D** [comment]
@Shine-neko after #2519, is it works ?

**Comment by Shine-neko** [comment]
@aRn0D With few odds :D

**Comment by aRn0D** [comment]
odds ?

**Comment by Shine-neko** [comment]
Hack *

**Comment by aRn0D** [comment]
Like ?
