### ISSUE TITLE
Sylius installer with sample data loading broken after PR #2481 merge

### ISSUE THREAD

**Issue by psyray** [Sylius/Sylius#2513]
Hi,

@pjedrzejewski 
FYI

Due to the merge of PR #2481, on a fresh install (app/console sylius:install), after loading sample datas, all the role/permission... tables were truncated.

So an error was returned while create administrator account on step 3 claims that role does not exists.
```
Installing Sylius...

Step 1 of 4. Checking system requirements.
+--------------------+----------------+
| Issue              | Recommendation |
+--------------------+----------------+
| short_open_tag     |                |
| session.auto_start |                |
+--------------------+----------------+
Success! Your system can run Sylius properly.

Step 2 of 4. Setting up the database.
Creating Sylius database for environment dev.
It appears that your database already exists. Would you like to reset it? (y/N) y

 1/7 [|||||                       ]  14%
 2/7 [|||||||||                   ]  28%
 3/7 [|||||||||||||               ]  42%
 4/7 [|||||||||||||||||           ]  57%
 5/7 [|||||||||||||||||||||       ]  71%
 6/7 [|||||||||||||||||||||||||   ]  85%
 7/7 [||||||||||||||||||||||||||||] 100%
Warning! This will erase your database. Your current environment is dev.
Load sample data? (y/N) y
Loading sample data...

 1/3 [||||||||||                  ]  33%
 2/3 [|||||||||||||||||||         ]  66%
 3/3 [||||||||||||||||||||||||||||] 100%

Step 3 of 4. Shop configuration.
Please enter list of locale codes, separated by commas or just hit ENTER to use "en_US". For example "en_US, de_DE".
In which language your customers can browse the store?  fr_FR
Adding français (France).
Please enter list of currency codes, separated by commas or just hit ENTER to use "USD". For example "USD, EUR, GBP".
In which currency your customers can buy goods?  EUR
Adding euro.

Please enter list of country codes, separated by commas or just hit ENTER to use "US". For example "US, PL, DE".
To which countries you are going to sell your goods?  FR
Adding France.
Create your administrator account.
Your firstname: ray
Lastname: ray
E-Mail: raynald@easi-services.fr
Choose password: test

Catchable fatal error: Argument 1 passed to Sylius\Component\Core\Model\User::addAuthorizationRole() must implement interface Sylius\Component\Rbac\Model\RoleInterface, null given, called in /opt/data/Eclipse/Sylius/Sylius/src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php on line 75 and defined in /opt/data/Eclipse/Sylius/Sylius/src/Sylius/Component/Core/Model/User.php on line 336

Call Stack:
    0.0002     233864   1. {main}() /opt/data/Eclipse/Sylius/Sylius/app/console:0
    0.0272    4094736   2. Symfony\Component\Console\Application->run() /opt/data/Eclipse/Sylius/Sylius/app/console:26
    0.0293    4290216   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /opt/data/Eclipse/Sylius/Sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:121
    0.2079   23054488   4. Symfony\Component\Console\Application->doRun() /opt/data/Eclipse/Sylius/Sylius/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
    0.2121   23055808   5. Symfony\Component\Console\Application->doRunCommand() /opt/data/Eclipse/Sylius/Sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
    0.2125   23083576   6. Symfony\Component\Console\Command\Command->run() /opt/data/Eclipse/Sylius/Sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:900
    0.2131   23106704   7. Sylius\Bundle\InstallerBundle\Command\InstallCommand->execute() /opt/data/Eclipse/Sylius/Sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:245
   80.5498  270979240   8. Sylius\Bundle\InstallerBundle\Command\CommandExecutor->runCommand() /opt/data/Eclipse/Sylius/Sylius/src/Sylius/Bundle/InstallerBundle/Command/InstallCommand.php:52
   80.5499  270980904   9. Symfony\Component\Console\Application->run() /opt/data/Eclipse/Sylius/Sylius/src/Sylius/Bundle/InstallerBundle/Command/CommandExecutor.php:71
   80.5500  270980952  10. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /opt/data/Eclipse/Sylius/Sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:121
   80.5502  270980952  11. Symfony\Component\Console\Application->doRun() /opt/data/Eclipse/Sylius/Sylius/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
   80.5541  270980904  12. Symfony\Component\Console\Application->doRunCommand() /opt/data/Eclipse/Sylius/Sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
   80.5541  270981144  13. Symfony\Component\Console\Command\Command->run() /opt/data/Eclipse/Sylius/Sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:900
   80.5543  270984352  14. Sylius\Bundle\InstallerBundle\Command\SetupCommand->execute() /opt/data/Eclipse/Sylius/Sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:245
   91.8292  271837264  15. Sylius\Bundle\InstallerBundle\Command\SetupCommand->setupAdministratorUser() /opt/data/Eclipse/Sylius/Sylius/src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php:48
  106.1007  271891248  16. Sylius\Component\Core\Model\User->addAuthorizationRole() /opt/data/Eclipse/Sylius/Sylius/src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php:75
```

If no sample datas loaded, eveything was fine, role/permission table was fully populated and installer runs fine, but no data in shop.

```
Installing Sylius...

Step 1 of 4. Checking system requirements.
+--------------------+----------------+
| Issue              | Recommendation |
+--------------------+----------------+
| short_open_tag     |                |
| session.auto_start |                |
+--------------------+----------------+
Success! Your system can run Sylius properly.

Step 2 of 4. Setting up the database.
Creating Sylius database for environment dev.
It appears that your database already exists. Would you like to reset it? (y/N) y

 1/7 [|||||                       ]  14%
 2/7 [|||||||||                   ]  28%
 3/7 [|||||||||||||               ]  42%
 4/7 [|||||||||||||||||           ]  57%
 5/7 [|||||||||||||||||||||       ]  71%
 6/7 [|||||||||||||||||||||||||   ]  85%
 7/7 [||||||||||||||||||||||||||||] 100%
Warning! This will erase your database. Your current environment is dev.
Load sample data? (y/N) n

Step 3 of 4. Shop configuration.
Please enter list of locale codes, separated by commas or just hit ENTER to use "en_US". For example "en_US, de_DE".
In which language your customers can browse the store?  fr_FR
Adding français (France).
Please enter list of currency codes, separated by commas or just hit ENTER to use "USD". For example "USD, EUR, GBP".
In which currency your customers can buy goods?  EUR
Adding euro.

Please enter list of country codes, separated by commas or just hit ENTER to use "US". For example "US, PL, DE".
To which countries you are going to sell your goods?  FR
Adding France.
Create your administrator account.
Your firstname: ray
Lastname: ray
E-Mail: raynald@easi-services.fr
Choose password: test

Step 4 of 4. Installing assets.
Installing Sylius assets for environment dev.

 1/2 [|||||||||||||||             ]  50%
 2/2 [||||||||||||||||||||||||||||] 100%

Sylius has been successfully installed.
You can now open your store at the following path under the website root: /app_dev.php.
```

**Comment by pjedrzejewski** [comment]
@psyray Thanks for reporting this! Fix on the way.

**Comment by pjedrzejewski** [comment]
Fixed in ffa9310.

**Comment by paceto256** [comment]
<code>

app/console sylius:install

Installing Sylius...

Step 1 of 4. Checking system requirements.
+------------------------------------+------------------------------------+
| Issue                              | Recommendation                     |
+------------------------------------+------------------------------------+
| sylius.settings.short_open_tag     |                                    |
| sylius.settings.session.auto_start |                                    |
| sylius.extensions.accelerator      | sylius.extensions.accelerator.help |
+------------------------------------+------------------------------------+
Success! Your system can run Sylius properly.

Step 2 of 4. Setting up the database.
Creating Sylius database for environment dev.
 4/4 [||||||||||||||||||||||||||||] 100%

Step 3 of 4. Shop configuration.
Please enter list of locale codes, separated by commas or just hit ENTER to use "en_US". For example "en_US, de_DE".
In which language your customers can browse the store?  bg_BG
Adding Bulgarian (Bulgaria).
Please enter list of currency codes, separated by commas or just hit ENTER to use "USD". For example "USD, EUR, GBP".
In which currency your customers can buy goods?  bg_BG 
This value is not a valid currency.
Please enter list of currency codes, separated by commas or just hit ENTER to use "USD". For example "USD, EUR, GBP".
In which currency your customers can buy goods?  BGN
Adding Bulgarian Lev.

Please enter list of country codes, separated by commas or just hit ENTER to use "US". For example "US, PL, DE".
To which countries you are going to sell your goods?  BG
Adding Bulgaria.
Create your administrator account.
Your firstname: Plamen
Lastname: Petrov
E-Mail: example@example.com
Choose password: secret
PHP Catchable fatal error:  Argument 1 passed to Sylius\Component\Core\Model\User::addAuthorizationRole() must implement interface Sylius\Component\Rbac\Model\RoleInterface, null given, called in /home/paceto/proj/sylius/src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php on line 75 and defined in /home/paceto/proj/sylius/src/Sylius/Component/Core/Model/User.php on line 336

</code>

**Comment by askyoh** [comment]
Hi, even with the fix, I still get the issue : 
 [Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 1 passed to Sylius\Component\Core\Model\User::addAuthorizationRole() must implement
  interface Sylius\Component\Rbac\Model\RoleInterface, null given, called in /var/www/gfw-over-sylius/vendor/sylius/sy
  lius/src/Sylius/Bundle/InstallerBundle/Command/SetupCommand.php on line 80 and defined

**Comment by pjedrzejewski** [comment]
Should be fixed in #2553.
