### ISSUE TITLE
can't set a default currency in general settings

### ISSUE THREAD

**Issue by amoraru** [Sylius/Sylius#2891]
When install sylius you're asked for a default currency, but that value is not set for the field Default currency in General Settings section

Worst is that even you add another currency, you can't select currency in Default currency select, because no option is being displayed.

![general settings](https://cloud.githubusercontent.com/assets/12938527/8226583/ae47c450-15a8-11e5-8c3b-73a1c76518cb.png)
![currencies](https://cloud.githubusercontent.com/assets/12938527/8226584/ae6c39e8-15a8-11e5-94b9-c80a4b576fed.png)

**Comment by nux** [comment]
This problem happens because the default channel when creating the store has no currency selected. A work around is to edit the default channel and select the currency.

When you do that, that currency becomes available in the settings. A proper fix would be to create the channel with the default currency selected.

**Comment by inssein** [comment]
This is actually a big problem, and took me a while to figure out. The problem isn't just with currencies, its also with the locale, and everything translation related in the backend becomes unusable.

The setup command needs to properly associate the channel with any currencies and locales created.

**Comment by pjedrzejewski** [comment]
Fixed in #3192.

**Comment by bretto36** [comment]
This is still an issue. I had an install of the dev version and i had to manually edit the db to get the shop to load. Currency, locale were both unset after following install

**Comment by bretto36** [comment]
This is still an issue. I had an install of the dev version and i had to manually edit the db to get the shop to load. Currency, locale were both unset after following install
