### ISSUE TITLE
[Bug] Error "This value is not valid" when tried to create a new page route

### ISSUE THREAD

**Issue by achristodoulou** [Sylius/Sylius#3963]
I cloned and installed Sylius on my machine.

1. I created a new page.

2. When I tried to create a route for the specified page I got the following error:

```
Message:
This value is not valid.

Origin:
parent

Cause:

Symfony\Component\Validator\ConstraintViolation
Object(Symfony\Component\Form\Form).children[parent] = /cms/routes

Caused by:

Symfony\Component\Form\Exception\TransformationFailedException
Unable to reverse value for property path "parent": Could not transform path "/cms/routes" to document. Path not found.

Caused by:

Symfony\Component\Form\Exception\TransformationFailedException
Could not transform path "/cms/routes" to document. Path not found.
```

**Comment by okwinza** [comment]
Related issue: Sylius/Sylius-Standard#78

Running `app/console doctrine:phpcr:repository:init` should solve this.

**Comment by kedves** [comment]
After updating the `composer.json` with `"symfony-cmf/routing-bundle": "1.4.*@dev"` should I re-init the project with `sylius:install`? Because the `doctrine:phpcr:repository:init` still doesn't initialize the CmfRoutingBundle.

**Comment by okwinza** [comment]
Ok so here is a temp fix untill #3967 is merged:

1) Ensure you have latest version of RoutingBundle as dep: 
`"symfony-cmf/routing-bundle": "1.4.*@dev"`

2) run `composer update`

3) Add this to your app config:
```
cmf_routing:
    chain:
        routers_by_id:
            router.default: 100
            sylius.dynamic_router: 50
            cmf_routing.dynamic_router: 20
    dynamic:
        generic_controller: cmf_content.controller:indexAction
        persistence:
            phpcr:
                enabled: true
                enable_initializer: true
                route_basepath: /cms/routes
```
4) Run `doctrine:phpcr:repository:init`

**Comment by gabiudrescu** [comment]
@okwinza from your knowledge, the tempfix requires Sylius 0.16 or is it fine with Sylius 0.15?

**Comment by pamil** [comment]
@gabiudrescu it should work on both 0.15 and 0.16, if only you have `1.4.*@dev` version of `symfony-cmf/routing-bundle`.

**Comment by gabiudrescu** [comment]
I ran into the error below, but I'm suspecting its due to our Satis:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package symfony-cmf/routing-bundle could not be found in any version, there may be a typo in the package name.
  Problem 2
    - sylius/sylius v0.15.0 requires symfony-cmf/routing-bundle ~1.2 -> no matching package found.
    - sylius/sylius v0.15.0 requires symfony-cmf/routing-bundle ~1.2 -> no matching package found.
    - Installation request for sylius/sylius 0.15.*@dev -> satisfiable by sylius/sylius[v0.15.0].
```

**Comment by okwinza** [comment]
@gabiudrescu tempfix has little to do with sylius itself, it is all about CMF Routing bundle.
You should be fine as long as you require latest version(1.4 or above).

**Comment by gabiudrescu** [comment]
yeah, I see. mainly, it was not about Sylius (codebase) but the dependencies and how they were solved. anyway, thanks everyone for the fast reply.
