### ISSUE TITLE
"Access Denied" when adding a new Entity as a Resource and call its route

### ISSUE THREAD

**Issue by itinance** [Sylius/Sylius#4792]
Following the [Documentation for Resource-Bundle ](http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/index.html) i stumbled upon an "access denied"-exception when accessing the generated routes for my new entity. I guess that this has something to do with RBAC-stuff, which is quiet undocumented. So i am not sure, if it will be a bug or a feature. If it is last one, some hints to fix missing permissions would be fine and helpful (not only here, especially at the Docs)

**Steps to reproduce:**

For this issue i started a complete new installation in order being sure that's not the result of side-issues on my own.

```
composer.phar create-project sylius/sylius-standard -s acme
cd acme
php app/console sylius:install

```
I added a new Entity named "Book" to the App-Bundle as shown in the documentation.

```
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use Sylius\Component\Resource\Model\ResourceInterface;

/**
 * Class Book
 * @ORM\Entity
 * @ORM\Table(name="book")
 */
class Book implements ResourceInterface
{
    /**
     * @var int
     * @ORM\Column(name="id", type="bigint")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=100, nullable=false)
     */
    protected $title;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param string $title
     * @return Book
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }
}

```

Then i configured "book" as a new resource in app/config/config.yml:

```
sylius_resource:
    resources:
        app.book:
            templates: AppBundle:Book
            classes:
                model: AppBundle\Entity\Book

```

I added the following lines to app/config/routing.yml:

```
app_book:
    resource: |
        alias: app.book
    type: sylius.resource

```

Running `php app/console debug:router` will list the new routes for my new entity Book:

```
app_book_index                                        GET              ANY      ANY    /books/                                                                   
app_book_create                                       GET|POST         ANY      ANY    /books/new                                                                
app_book_update                                       GET|PUT|PATCH    ANY      ANY    /books/{id}/edit                                                          
app_book_show                                         GET              ANY      ANY    /books/{id}                                                               
app_book_delete                                       DELETE           ANY      ANY    /books/{id}                                                               

```

With a running server i logged in to my user, which is administrator having root-privileges, i can navigate around the whole site. But when i want to access the route "/books", an "Access Denied"-Error will be thrown.

As stated at the beginning, maybe this is not a bug but a missing lag in the documentation and should be clarified.

**Comment by itinance** [comment]
Digging around in other issues i found out, that with a special setting "permissions: false" the resource will be available without any permissions-check and thus without "Access Denied". 
But the main question according to RBAC-configuration remains.

```
app_book:
   resource: |
       alias: app.book
   type: sylius.resource
   defaults:
        _sylius:
            permission: false

```

**Comment by inssein** [comment]
I don't know if it is in the docs, but I had to define my permissions (look at CoreBundle/Resources/config/app/sylius.yml, specifically the sylius_rbac: bits), and then i had to run ```sylius:rbac:initialize```

**Comment by pjedrzejewski** [comment]
Should be resolved, as Rbac has been removed.

**Comment by itinance** [comment]
Rbac has been removed? Please correct me if i'm wrong, but on in 0.19 it is still present

**Comment by pjedrzejewski** [comment]
Please see http://sylius.org/blog/sylius-roadmap-update. Sorry for the trouble, you can still bring back the functionality with a standalone bundle.
