### ISSUE TITLE
cancel an order also refund 

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#6144]
A customer may cancel his order immediately after he payed, we need to cancel this order as well as refund the money back.  the states for current order are:

```
current order
state: new
paymentState: payed
shippingState: ready

last payment
state: completed

last shipment:
state: ready

```
  We can't cancel this order directly,  because this order is payed , and  we can only cancel a payment when its state is new or processing, we can refund the money back at this time,  but how can we mark this order canceled as well?

**Comment by michalmarcinkowski** [comment]
Should be resolved by https://github.com/Sylius/Sylius/pull/6192, please reopen if there are any more issues.

**Comment by videni** [comment]
@michalmarcinkowski , I reopen this issue, because a paid order still can't be cancelled.

**Comment by michalmarcinkowski** [comment]
On master a paid order can be cancelled, we have a scenario for that (see [here](https://github.com/Sylius/Sylius/blob/master/features/inventory/verify_reserved_inventory_is_back_in_stock_on_order_cancelling.feature#L32)).

**Comment by videni** [comment]
@michalmarcinkowski , cancelling a paid order also means  refunding the money, but I don't find  any code to handle this logic. by the way, it seems I misunderstand  that the state  of a payment of a paid order should be state `processing` ,not `completed` ,right?  otherwise, the payment can't be cancelled, I infer this information from these code below. please correct me if I am wrong, thank you.

```
winzou_state_machine:
    sylius_payment:
        class: "%sylius.model.payment.class%"
        property_path: state
        graph: sylius_payment
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            new: ~
            processing: ~
            completed: ~
            failed: ~
            cancelled: ~
            void: ~
            refunded: ~
        transitions:
            create:
                from: [cart]
                to: new
            process:
                from: [new]
                to: processing
            complete:
                from: [new, processing]
                to: completed
            fail:
                from: [new, processing]
                to: failed
            cancel:
                from: [new, processing]
                to: cancelled
            refund:
                from: [completed]
                to: refunded
            void:
                from: [new, processing]
                to: void
```

**Comment by pjedrzejewski** [comment]
@videni Currently you need to handle that manually. We do not have any refund logic yet.

**Comment by videni** [comment]
@pjedrzejewski @michalmarcinkowski , since this is a new feature, can we reopen this issue?
