### ISSUE TITLE
product_from_taxon.yml

### ISSUE THREAD

**Issue by khalidahmada** [Sylius/Sylius#7428]
I try to install Sylius but i have an error after projet installed

"/vendor/sylius/sylius/src/Sylius/Bund    
    le/AdminBundle/Resources/config/grids/product_from_taxon.yml"
![capture d ecran 2017-02-06 a 15 57 14](https://cloud.githubusercontent.com/assets/2378611/22658397/d40bb310-ec91-11e6-999d-01ad214f5c69.png)

**Comment by pjedrzejewski** [comment]
@khalidahmada Could you tell us more about your env, please? :)

**Comment by pamil** [comment]
@khalidahmada it's already fixed in `dev-master`, see #7000 :)

**Comment by khalidahmada** [comment]
@pjedrzejewski thank you fo your replay. Ok so i'm on MAC OS El capitan  PHP 5.6.27 Composer version 1.3.0

**Comment by michalmarcinkowski** [comment]
Please try on `dev-master` branch and reopen if still occurs.
