### ISSUE TITLE
ProductTaxon position is lost after editing a product

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/Sylius#7446]
Steps to reproduce
-------------------

1. Go to http://demo.sylius.org/admin/products
2. Select a taxon in the left menu
3. Edit product with position 0
4. Save
5. Now product that was at position 0 is the last one

![sylius-bug](https://cloud.githubusercontent.com/assets/1749891/22702823/485bb078-ed62-11e6-9202-f37685769b40.gif)

**Comment by mbabker** [comment]
Possibly related?  Getting this error saving existing products:

```sh
An exception occurred while executing 'INSERT INTO sylius_product_taxon (position, product_id, taxon_id) VALUES (?, ?, ?)' with params [81, 291, 4]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '291-4' for key 'product_taxon_idx'
```

**Comment by liverbool** [comment]
Critical Bug!!

**Comment by liverbool** [comment]
@Sylius, we can't save update product!

ping @pjedrzejewski

**Comment by pjedrzejewski** [comment]
@liverbool Fix incoming from @Arminek! :)

**Comment by pjedrzejewski** [comment]
Fixed in #7516, could you confirm @liverbool @gorkalaucirica?

**Comment by gorkalaucirica** [comment]
I tried to reproduce the bug in master and it seems fixed. I will keep an eye on it an report back if we see same strange behavior.

Thanks!!!

**Comment by c-revillo** [comment]
Hello, i still have the error @mbabker has pointed out... is there any other issue for this?
