### ISSUE TITLE
Can't add a new product in a taxon

### ISSUE THREAD

**Issue by aimeric** [Sylius/Sylius#8130]
Hi,

I have been trying to add a new product in a category , but I can't see the sub categories under category.

On the sylius demo its looks as below:

![sylius1](https://cloud.githubusercontent.com/assets/5352387/26755117/2b88d55e-4887-11e7-9534-7f8ad6e153ad.jpg)

In my back-end its look like this:

![sylius2](https://cloud.githubusercontent.com/assets/5352387/26755143/bf8fe8b4-4887-11e7-8bf9-bf5d12b8fee9.jpg)

I'm using sylius 1.0.0-beta.2

**Comment by smashou** [comment]
Have you deployed with yarn the admin assets ?

**Comment by aimeric** [comment]
@smashou ,  Yes I did run yarn , but It didn't work. After running `php bin/console sylius:fixtures:load` it fixed the issue, but now the thumbnail (`sylius_shop_product_thumbnail`) of the latest products doesn't show up.

Before to run `sylius:fixtures:load ` all the thumbnail were loaded properly.

The path to the picture seems to be ok.

The thumbnail are not generated in `media/cache`

**config.yml**
```

liip_imagine :
    resolvers :
        default :
            web_path :
                web_root: "%kernel.root_dir%/../web"
                cache_prefix: "media/cache"

    filter_sets :
        cache : ~
        sylius_shop_product_original: ~
        sylius_shop_product_tiny_thumbnail:
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        sylius_shop_product_small_thumbnail:
            filters:
                thumbnail: { size: [150, 112], mode: outbound }
        sylius_shop_product_thumbnail:
            filters:
                thuimbnail: { size: [260, 260], mode: outbound }
        sylius_shop_product_large_thumbnail:
            filters:
                thumbnail: { size: [550, 412], mode: outbound }
```

**Comment by pcmdev** [comment]
Same issue here, no taxonomy term tree displayed.

**Comment by smashou** [comment]
It seems that the route "sylius_admin_ajax_taxon_leafs" which call findChildren method from TaxonRepository is not working well.

**Comment by aimeric** [comment]
@pcmdev , It seems like not all the fixtures are loaded properly while running  `php bin/console sylius:fixtures:load`

I fixed my this issue by adding this line into `bin/console.php`

`ini_set('memory_limit','-1');`

Follow the steps below:

1. `composer create-project -s beta sylius/sylius-standard sylius`
2. add this line :  `ini_set('memory_limit','-1');` into `console.php `
3. `php bin/console sylius:install`
4. `npm install --global yarn`
5. `yarn install`
6. `yarn add node-sass`
7. `yarn run gulp`

let me know if it works.

**Comment by pcmdev** [comment]
Are you guys using any custom locale on your shop? I've tried installing a new version and it works OK. On the none working version I'm using en_GB and on the working one en_US. There is a query running to find the leafs where one of the WHERE clauses try to match en_US that I don't have on that version.

**Comment by smashou** [comment]
I'm using fr_FR and en_US and still not working. And I have an en_US translation on each of my taxon

**Comment by pcmdev** [comment]
There is a quick way to fix it editing the table "sylius_taxon_translation" and setting the locale to "en_US" in my case, and the tree will be displayed correctly, at least that worked for me. Although I'm not sure how to fix it for new ones.

**Comment by smashou** [comment]
For me the quick fix was to override the findChildren and remove the locale from the request. I think it's just a small fix. But I do not have enough time today to fix it. I'll give a try tomorrow :)

**Comment by pcmdev** [comment]
Just to add an additional comment. When the translation is there the taxonomy tree is rendered, but not completely, it's just displaying the children of top level taxonomies. That happening even on the default Sylius installation.

**Comment by gabiudrescu** [comment]
isn't this related to #8068?

**Comment by pcmdev** [comment]
I think there are two independent bugs on this ticket:

- The query not getting the categories if the translation is not set correctly.
- The rendering of the tree.

The second one is on these files:

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-lazy-choice-tree.js

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js

`$('#sylius-product-taxonomy-tree').choiceTree('productTaxon', true, 1);`

What's the logic to limit the rendering of the tree with DefaultLevel = 1? This way only the root categories and the immediate children are rendered, is this done on purpose for performance? Removing the if check on line 112 of the first file fixes the issue. Or just incrementing de defaultLevel to the appropriate depth.

**Comment by pcmdev** [comment]
@smashou @gabiudrescu there is an easy way to fix the issue related to the categories problem without overriding the getChildren method. The actual "bug" is that the admin user Sylius is creating during the installation has the locale en_US, and therefore it tries to find categories with that locale on the admin. Changing the local of your admin user to en_GB in my case fixed the issue straight away, because the only locale available on my website is en_GB.

**Comment by gabiudrescu** [comment]
@pcmdev yup, I confirm. this is the correct way to reproduce the bug(s)!

**Comment by bitbager** [comment]
@Arminek, that's exactly the bug I was trying to explain you in Berlin! :D

**Comment by ccvf2s** [comment]
Good evening,

This is not solved we still have an issue with the JS, https://github.com/Sylius/SyliusAdminBundle/blob/1.3/Resources/private/js/app.js#L86

Why the level is one? Why not rendering all the taxonomies?

Thanks a lot for the help,
Dimitri.
