### ISSUE TITLE
[Bug] [Admin] SQL error on selecting variants for product image

### ISSUE THREAD

**Issue by mrjingles** [Sylius/Sylius#8336]
Actually I cannot select variants for a product image. It seems to be an error in SQL syntax:

The query looks like:
`SELECT [..]
FROM sylius_product_variant s0_ INNER JOIN sylius_product s1_ ON s0_.product_id = s1_.id
WHERE s1_.code = "foobar" AND s0_.code = "foo", "bar";`

but it has to be:
`SELECT [..]
FROM sylius_product_variant s0_ INNER JOIN sylius_product s1_ ON s0_.product_id = s1_.id
WHERE s1_.code = "foobar" AND s0_.code IN ("foo", "bar");`

**Comment by mrjingles** [comment]
I am not sure, why its broken again, but it has to do with accessing the repository.

1) Already selected variants are not shown because of the missing IN() in query builder: ProductVariantRepository::findByCodeAndProductCode()

2) Available options are not shown because repository method ProductVariantRepository::findByPhraseAndProductCode() is accessed without phrase.

Hope that helps.

**Comment by mrjingles** [comment]
@pjedrzejewski This is still a bug. Why is it removed from v1.0.0?

**Comment by pjedrzejewski** [comment]
@mrjingles Misclick, I was updating many issues. :)

**Comment by mrjingles** [comment]
@pjedrzejewski Ok. Thx for bringing it back. ;-)

**Comment by pjedrzejewski** [comment]
@mrjingles Fixed by @GSadee in #8506. :) Thanks for reporting! 👍

**Comment by mrjingles** [comment]
Hi @pjedrzejewski Thx for your work. Point 1) in my comment seems to be fixed. Point 2) is still not fixed. I cannot select any variants for images. Can you re-open or should I create a new issue?

**Comment by GSadee** [comment]
Hi @mrjingles. Could you tell us sth more about point 2) because I cannot recreate this bug? 
Phrase is the text which you write in the input, so if you don't write anything, then the phrase is empty and all variants for given product should be displayed. 

My only thought is... Did you do:
```
$ yarn install
$ yarn run gulp
```
in your project?

**Comment by mrjingles** [comment]
Hi @GSadee I took another deeper look into it. Problem is, that I switched from locale format "xx_XX" to "xx". Actually, I cannot see why, but the repository method is getting "xx_XX". So I have to check where still old locale format is in my DB or whatever.

I close the issue. TY!
