### ISSUE TITLE
Cart summary implementation for Mobile / Responsive 

### ISSUE THREAD

**Issue by othbert** [Sylius/Sylius#8907]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1

Just making a note of some bad design breaks in the cart summary view on mobile and tablet. Coupon code field causes all sorts of issues with it's width being too large for containing elements.

**Comment by pakulin** [comment]
form "sylius_cart" unresposive (on demo.sylius.com)

![screen shot 2018-03-26 at 14 40 13](https://user-images.githubusercontent.com/5189335/37904258-e0504c46-3103-11e8-84e6-a26b80266966.png)

**Comment by Zales0123** [comment]
There was some work already done my @NeverResponse https://github.com/Sylius/Sylius/pull/8057 but it was abandoned, unfortunately... @othbert @pakulin maybe some of you are willing to continue work with this PR? 😄 It would be very nice to have some UI fixes done, especially when they're so nasty

**Comment by pamil** [comment]
@pakulin I'd rather keep my weekends for non-work related activities, gamification won't change that. Our default template is being reworked right now, so this issue would probably be solved by that.

**Comment by othbert** [comment]
just checked https://demo.sylius.com/en_US/cart/
issue still exists
